name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # 매일 00:00 UTC에 실행

  workflow_dispatch: # 수동 실행 가능

jobs:
  snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ✅ GITHUB_TOKEN에 write 권한 추가

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ji-0o0o0o0
          outputs: dist/snake.svg  

      - name: Debug snake generation
        run: ls -la dist/ || echo "dist/snake.svg not found"

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake animation"
          add: "dist/snake.svg"
          default_author: github_actions
